import uuid
from datetime import date, datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.patient import Patient

SEED_PATIENTS = [
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e01"),
        "first_name": "Maria",
        "last_name": "Santos",
        "date_of_birth": date(1958, 3, 14),
        "gender": "Female",
        "email": "maria.santos@example.com",
        "phone": "555-0101",
        "address": "142 Elm Street, Boston, MA 02101",
        "blood_type": "O+",
        "allergies": ["penicillin"],
        "conditions": ["hypertension", "type 2 diabetes"],
        "status": "active",
        "last_visit_date": datetime(2026, 2, 10, 9, 30, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e02"),
        "first_name": "James",
        "last_name": "Okafor",
        "date_of_birth": date(1990, 7, 22),
        "gender": "Male",
        "email": "james.okafor@example.com",
        "phone": "555-0102",
        "address": "88 Maple Ave, Cambridge, MA 02139",
        "blood_type": "A+",
        "allergies": [],
        "conditions": ["asthma"],
        "status": "active",
        "last_visit_date": datetime(2026, 1, 28, 14, 0, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e03"),
        "first_name": "Priya",
        "last_name": "Patel",
        "date_of_birth": date(1975, 11, 3),
        "gender": "Female",
        "email": "priya.patel@example.com",
        "phone": "555-0103",
        "address": "201 Oak Lane, Somerville, MA 02143",
        "blood_type": "B+",
        "allergies": ["sulfa drugs", "latex"],
        "conditions": ["COPD"],
        "status": "critical",
        "last_visit_date": datetime(2026, 2, 20, 11, 15, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e04"),
        "first_name": "Robert",
        "last_name": "Chen",
        "date_of_birth": date(1942, 5, 18),
        "gender": "Male",
        "email": "robert.chen@example.com",
        "phone": "555-0104",
        "address": "55 Pine Road, Brookline, MA 02445",
        "blood_type": "AB+",
        "allergies": ["aspirin"],
        "conditions": ["coronary artery disease", "hypertension", "hyperlipidemia"],
        "status": "active",
        "last_visit_date": datetime(2026, 2, 5, 8, 45, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e05"),
        "first_name": "Fatima",
        "last_name": "Al-Rashid",
        "date_of_birth": date(1988, 9, 7),
        "gender": "Female",
        "email": "fatima.alrashid@example.com",
        "phone": "555-0105",
        "address": "310 Cedar Blvd, Newton, MA 02458",
        "blood_type": "O-",
        "allergies": [],
        "conditions": [],
        "status": "active",
        "last_visit_date": datetime(2025, 12, 15, 10, 0, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e06"),
        "first_name": "William",
        "last_name": "Thompson",
        "date_of_birth": date(1955, 1, 30),
        "gender": "Male",
        "email": "william.thompson@example.com",
        "phone": "555-0106",
        "address": "78 Birch Street, Quincy, MA 02169",
        "blood_type": "A-",
        "allergies": ["peanuts", "shellfish"],
        "conditions": ["type 2 diabetes", "peripheral neuropathy"],
        "status": "active",
        "last_visit_date": datetime(2026, 2, 18, 13, 30, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e07"),
        "first_name": "Yuki",
        "last_name": "Tanaka",
        "date_of_birth": date(1998, 4, 12),
        "gender": "Female",
        "email": "yuki.tanaka@example.com",
        "phone": "555-0107",
        "address": "425 Walnut Drive, Medford, MA 02155",
        "blood_type": None,
        "allergies": [],
        "conditions": ["generalized anxiety disorder"],
        "status": "active",
        "last_visit_date": datetime(2026, 1, 10, 15, 0, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e08"),
        "first_name": "Carlos",
        "last_name": "Rivera",
        "date_of_birth": date(1970, 8, 25),
        "gender": "Male",
        "email": "carlos.rivera@example.com",
        "phone": "555-0108",
        "address": "162 Spruce Way, Malden, MA 02148",
        "blood_type": "B-",
        "allergies": ["penicillin", "ibuprofen"],
        "conditions": ["chronic kidney disease", "hypertension"],
        "status": "critical",
        "last_visit_date": datetime(2026, 2, 22, 9, 0, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e09"),
        "first_name": "Sarah",
        "last_name": "Johnson",
        "date_of_birth": date(1983, 12, 1),
        "gender": "Female",
        "email": "sarah.johnson@example.com",
        "phone": "555-0109",
        "address": "93 Hickory Lane, Arlington, MA 02474",
        "blood_type": "O+",
        "allergies": [],
        "conditions": ["hypothyroidism"],
        "status": "active",
        "last_visit_date": None,
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e0a"),
        "first_name": "David",
        "last_name": "Kim",
        "date_of_birth": date(1965, 6, 19),
        "gender": "Male",
        "email": "david.kim@example.com",
        "phone": "555-0110",
        "address": "507 Ash Court, Waltham, MA 02451",
        "blood_type": "AB-",
        "allergies": ["latex"],
        "conditions": ["osteoarthritis", "benign prostatic hyperplasia"],
        "status": "inactive",
        "last_visit_date": datetime(2025, 8, 20, 11, 0, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e0b"),
        "first_name": "Aisha",
        "last_name": "Mohammed",
        "date_of_birth": date(2001, 2, 14),
        "gender": "Female",
        "email": "aisha.mohammed@example.com",
        "phone": "555-0111",
        "address": "234 Poplar Street, Revere, MA 02151",
        "blood_type": "A+",
        "allergies": ["peanuts"],
        "conditions": [],
        "status": "active",
        "last_visit_date": datetime(2026, 2, 1, 10, 30, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e0c"),
        "first_name": "Michael",
        "last_name": "O'Brien",
        "date_of_birth": date(1950, 10, 8),
        "gender": "Male",
        "email": "michael.obrien@example.com",
        "phone": "555-0112",
        "address": "671 Chestnut Ave, Watertown, MA 02472",
        "blood_type": "O+",
        "allergies": ["sulfa drugs", "codeine"],
        "conditions": ["atrial fibrillation", "congestive heart failure"],
        "status": "critical",
        "last_visit_date": datetime(2026, 2, 23, 8, 0, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e0d"),
        "first_name": "Lin",
        "last_name": "Wei",
        "date_of_birth": date(1993, 3, 27),
        "gender": "Female",
        "email": "lin.wei@example.com",
        "phone": "555-0113",
        "address": "118 Magnolia Road, Belmont, MA 02478",
        "blood_type": "B+",
        "allergies": [],
        "conditions": ["iron deficiency anemia"],
        "status": "active",
        "last_visit_date": datetime(2026, 1, 22, 14, 30, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e0e"),
        "first_name": "Thomas",
        "last_name": "Williams",
        "date_of_birth": date(1948, 7, 4),
        "gender": "Male",
        "email": "thomas.williams@example.com",
        "phone": "555-0114",
        "address": "890 Willow Street, Lexington, MA 02420",
        "blood_type": "A+",
        "allergies": ["penicillin", "erythromycin"],
        "conditions": ["COPD", "type 2 diabetes", "glaucoma"],
        "status": "active",
        "last_visit_date": datetime(2026, 2, 12, 9, 15, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e0f"),
        "first_name": "Sofia",
        "last_name": "Morales",
        "date_of_birth": date(1979, 5, 16),
        "gender": "Female",
        "email": "sofia.morales@example.com",
        "phone": "555-0115",
        "address": "345 Sycamore Drive, Everett, MA 02149",
        "blood_type": None,
        "allergies": ["latex", "contrast dye"],
        "conditions": ["migraine", "fibromyalgia"],
        "status": "active",
        "last_visit_date": datetime(2026, 2, 8, 16, 0, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e10"),
        "first_name": "Andre",
        "last_name": "Baptiste",
        "date_of_birth": date(1986, 11, 22),
        "gender": "Male",
        "email": "andre.baptiste@example.com",
        "phone": "555-0116",
        "address": "56 Redwood Lane, Chelsea, MA 02150",
        "blood_type": "O+",
        "allergies": [],
        "conditions": ["sickle cell trait"],
        "status": "inactive",
        "last_visit_date": datetime(2025, 6, 30, 10, 0, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e11"),
        "first_name": "Elena",
        "last_name": "Volkov",
        "date_of_birth": date(1962, 9, 3),
        "gender": "Female",
        "email": "elena.volkov@example.com",
        "phone": "555-0117",
        "address": "789 Juniper Court, Woburn, MA 01801",
        "blood_type": "AB+",
        "allergies": ["morphine"],
        "conditions": ["rheumatoid arthritis", "osteoporosis"],
        "status": "active",
        "last_visit_date": datetime(2026, 2, 15, 11, 45, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e12"),
        "first_name": "Daniel",
        "last_name": "Nguyen",
        "date_of_birth": date(2004, 1, 9),
        "gender": "Male",
        "email": "daniel.nguyen@example.com",
        "phone": "555-0118",
        "address": "412 Cypress Street, Stoneham, MA 02180",
        "blood_type": "A-",
        "allergies": ["peanuts", "tree nuts"],
        "conditions": ["asthma", "eczema"],
        "status": "active",
        "last_visit_date": datetime(2026, 1, 5, 13, 0, tzinfo=timezone.utc),
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e13"),
        "first_name": "Grace",
        "last_name": "Adeyemi",
        "date_of_birth": date(1973, 4, 20),
        "gender": "Female",
        "email": "grace.adeyemi@example.com",
        "phone": "555-0119",
        "address": "267 Beech Avenue, Winchester, MA 01890",
        "blood_type": "B+",
        "allergies": [],
        "conditions": ["hypertension", "uterine fibroids"],
        "status": "active",
        "last_visit_date": None,
    },
    {
        "id": uuid.UUID("b0a3e426-1d3a-4b0e-9b0a-1a2b3c4d5e14"),
        "first_name": "Patrick",
        "last_name": "Murphy",
        "date_of_birth": date(1940, 12, 28),
        "gender": "Male",
        "email": "patrick.murphy@example.com",
        "phone": "555-0120",
        "address": "133 Hawthorn Place, Stoughton, MA 02072",
        "blood_type": "O-",
        "allergies": ["aspirin", "NSAIDs"],
        "conditions": ["Parkinson's disease", "hypertension", "chronic pain"],
        "status": "critical",
        "last_visit_date": datetime(2026, 2, 21, 8, 30, tzinfo=timezone.utc),
    },
]


async def seed_patients(db: AsyncSession) -> None:
    result = await db.execute(select(Patient).limit(1))
    if result.scalars().first() is not None:
        return

    for data in SEED_PATIENTS:
        db.add(Patient(**data))
